[pytest]
addopts = 
    ; --html=test-results/report.html
    ; --self-contained-html
    -v
    ; --strict-markers
    ; --tb=short
    ; --disable-warnings
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
	auto_login: auto login tests
    smoke: smoke tests
    regression: regression tests
    gui: GUI tests
    slow: slow tests
    integration: integration tests
